FROM cypress/included:14.5.0

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY cypress.config.js ./

RUN npm ci

COPY cypress ./cypress

RUN mkdir -p cypress-results

EXPOSE 9323

CMD ["npx", "cypress", "run"] 