services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./angular.json:/app/angular.json
      - ./tsconfig.json:/app/tsconfig.json
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    container_name: cypress-tests
    depends_on:
      angular-app:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://angular-app:4200
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.config.js:/app/cypress.config.js
      - ./cypress-results:/app/cypress-results
    networks:
      - backend
    command: npx cypress run --spec "cypress/e2e/**/*.cy.js" --reporter junit --reporter-options "mochaFile=cypress-results/results.xml,toConsole=true"

networks:
  backend:
    external: true
    name: task-manager-system_backend 